<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // Create Admin User
        User::create([
            'name' => 'مدير النظام',
            'email' => 'admin@empapy.com',
            'password' => bcrypt('password'),
            'role' => 'admin',
            'phone' => '+20 100 123 4567',
        ]);

        // Create Test Customer
        User::create([
            'name' => 'أحمد محمد',
            'email' => 'customer@empapy.com',
            'password' => bcrypt('password'),
            'role' => 'customer',
            'phone' => '+20 100 987 6543',
            'address' => '15 شارع التحرير، وسط البلد',
            'city' => 'القاهرة',
            'governorate' => 'القاهرة',
        ]);

        // Create Categories
        $categories = [
            [
                'name' => 'Espresso Blends',
                'name_ar' => 'خلطات الإسبريسو',
                'slug' => 'espresso-blends',
                'description' => 'Premium espresso blends for the perfect shot',
                'description_ar' => 'خلطات إسبريسو فاخرة للحصول على أفضل كوب قهوة',
                'image' => 'https://images.unsplash.com/photo-1610889556528-9a770e32642f?w=400&h=400&fit=crop',
            ],
            [
                'name' => 'Single Origin',
                'name_ar' => 'قهوة أحادية المصدر',
                'slug' => 'single-origin',
                'description' => 'Carefully sourced beans from the world\'s finest regions',
                'description_ar' => 'حبوب قهوة مختارة بعناية من أفضل مناطق العالم',
                'image' => 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=400&h=400&fit=crop',
            ],
            [
                'name' => 'Flavored Coffee',
                'name_ar' => 'قهوة منكّهة',
                'slug' => 'flavored-coffee',
                'description' => 'Delicious flavored coffee varieties',
                'description_ar' => 'أنواع قهوة منكّهة لذيذة ومميزة',
                'image' => 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=400&fit=crop',
            ],
            [
                'name' => 'Cold Brew',
                'name_ar' => 'القهوة الباردة',
                'slug' => 'cold-brew',
                'description' => 'Smooth and refreshing cold brew coffee',
                'description_ar' => 'قهوة باردة منعشة وناعمة',
                'image' => 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=400&h=400&fit=crop',
            ],
            [
                'name' => 'Arabic Coffee',
                'name_ar' => 'القهوة العربية',
                'slug' => 'arabic-coffee',
                'description' => 'Traditional Arabic coffee with cardamom',
                'description_ar' => 'قهوة عربية تقليدية بالهيل',
                'image' => 'https://images.unsplash.com/photo-1578374173705-969cbe6f2d6b?w=400&h=400&fit=crop',
            ],
        ];

        foreach ($categories as $category) {
            Category::create($category);
        }

        // Create Products
        $products = [
            // Espresso Blends
            [
                'category_id' => 1,
                'name' => 'Italian Espresso Blend',
                'name_ar' => 'خلطة إسبريسو إيطالية',
                'slug' => 'italian-espresso-blend',
                'description' => 'Rich and intense Italian-style espresso with notes of dark chocolate and caramel. Perfect for a strong morning cup.',
                'description_ar' => 'إسبريسو إيطالي غني ومكثف مع نكهات الشوكولاتة الداكنة والكراميل. مثالي لفنجان صباحي قوي.',
                'price' => 350.00,
                'sale_price' => 299.00,
                'image' => 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop',
                'stock' => 50,
                'weight' => '500g',
                'roast_level' => 'dark',
                'origin' => 'Blend',
                'origin_ar' => 'مزيج',
                'is_featured' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'Espresso Double Shot',
                'name_ar' => 'إسبريسو مزدوج',
                'slug' => 'espresso-double-shot',
                'description' => 'Extra strong espresso blend for coffee lovers who need that extra kick.',
                'description_ar' => 'خلطة إسبريسو قوية جداً لعشاق القهوة الذين يحتاجون إلى دفعة إضافية.',
                'price' => 380.00,
                'image' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&h=400&fit=crop',
                'stock' => 40,
                'weight' => '500g',
                'roast_level' => 'dark',
                'origin' => 'Blend',
                'origin_ar' => 'مزيج',
                'is_featured' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'French Roast Premium',
                'name_ar' => 'تحميص فرنسي فاخر',
                'slug' => 'french-roast-premium',
                'description' => 'Smoky and bold with dark chocolate notes. A classic French roast experience.',
                'description_ar' => 'مدخنة وجريئة مع نكهات الشوكولاتة الداكنة. تجربة تحميص فرنسي كلاسيكية.',
                'price' => 320.00,
                'image' => 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=400&h=400&fit=crop',
                'stock' => 60,
                'weight' => '500g',
                'roast_level' => 'dark',
                'origin' => 'Blend',
                'origin_ar' => 'مزيج',
            ],

            // Single Origin
            [
                'category_id' => 2,
                'name' => 'Ethiopian Yirgacheffe',
                'name_ar' => 'إثيوبي يرغاشيفي',
                'slug' => 'ethiopian-yirgacheffe',
                'description' => 'Bright and fruity with notes of blueberry, citrus, and floral undertones. From the birthplace of coffee.',
                'description_ar' => 'قهوة مشرقة وفاكهية مع نكهات التوت الأزرق والحمضيات والزهور. من مسقط رأس القهوة.',
                'price' => 450.00,
                'sale_price' => 399.00,
                'image' => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=400&fit=crop',
                'stock' => 35,
                'weight' => '250g',
                'roast_level' => 'light',
                'origin' => 'Ethiopia',
                'origin_ar' => 'إثيوبيا',
                'is_featured' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'Colombian Supremo',
                'name_ar' => 'كولومبي سوبريمو',
                'slug' => 'colombian-supremo',
                'description' => 'Smooth and balanced with caramel sweetness and nutty undertones.',
                'description_ar' => 'قهوة ناعمة ومتوازنة مع حلاوة الكراميل ونكهات المكسرات.',
                'price' => 380.00,
                'image' => 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=400&fit=crop',
                'stock' => 45,
                'weight' => '500g',
                'roast_level' => 'medium',
                'origin' => 'Colombia',
                'origin_ar' => 'كولومبيا',
                'is_featured' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'Kenyan AA Premium',
                'name_ar' => 'كيني AA الفاخر',
                'slug' => 'kenyan-aa-premium',
                'description' => 'Wine-like acidity with blackcurrant notes and a complex, fruity finish.',
                'description_ar' => 'حموضة تشبه النبيذ مع نكهات الكشمش الأسود ونهاية فاكهية معقدة.',
                'price' => 520.00,
                'image' => 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=400&h=400&fit=crop',
                'stock' => 25,
                'weight' => '250g',
                'roast_level' => 'medium',
                'origin' => 'Kenya',
                'origin_ar' => 'كينيا',
            ],
            [
                'category_id' => 2,
                'name' => 'Brazilian Santos',
                'name_ar' => 'برازيلي سانتوس',
                'slug' => 'brazilian-santos',
                'description' => 'Nutty and chocolatey with low acidity. Perfect for everyday drinking.',
                'description_ar' => 'نكهة المكسرات والشوكولاتة مع حموضة منخفضة. مثالية للشرب اليومي.',
                'price' => 290.00,
                'image' => 'https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=400&h=400&fit=crop',
                'stock' => 70,
                'weight' => '1kg',
                'roast_level' => 'medium',
                'origin' => 'Brazil',
                'origin_ar' => 'البرازيل',
            ],
            [
                'category_id' => 2,
                'name' => 'Sumatra Mandheling',
                'name_ar' => 'سومطرة ماندلينج',
                'slug' => 'sumatra-mandheling',
                'description' => 'Full-bodied with earthy, herbal notes and a smooth, syrupy finish.',
                'description_ar' => 'قهوة كاملة القوام مع نكهات ترابية وعشبية ونهاية ناعمة.',
                'price' => 420.00,
                'image' => 'https://images.unsplash.com/photo-1504630083234-14187a9df0f5?w=400&h=400&fit=crop',
                'stock' => 30,
                'weight' => '500g',
                'roast_level' => 'dark',
                'origin' => 'Indonesia',
                'origin_ar' => 'إندونيسيا',
            ],
            [
                'category_id' => 2,
                'name' => 'Costa Rican Tarrazu',
                'name_ar' => 'كوستاريكا تارازو',
                'slug' => 'costa-rican-tarrazu',
                'description' => 'Bright acidity with honey and citrus notes. Clean and vibrant.',
                'description_ar' => 'حموضة مشرقة مع نكهات العسل والحمضيات. نظيفة وحيوية.',
                'price' => 480.00,
                'image' => 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=400&h=400&fit=crop',
                'stock' => 28,
                'weight' => '250g',
                'roast_level' => 'light',
                'origin' => 'Costa Rica',
                'origin_ar' => 'كوستاريكا',
            ],
            [
                'category_id' => 2,
                'name' => 'Panama Geisha Reserve',
                'name_ar' => 'بنما جيشا الاحتياطي',
                'slug' => 'panama-geisha-reserve',
                'description' => 'Rare and exotic with jasmine, bergamot, and tropical fruit notes.',
                'description_ar' => 'نادرة وغريبة مع الياسمين والبرغموت وفواكه استوائية.',
                'price' => 850.00,
                'image' => 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop',
                'stock' => 10,
                'weight' => '250g',
                'roast_level' => 'light',
                'origin' => 'Panama',
                'origin_ar' => 'بنما',
                'is_featured' => true,
            ],

            // Flavored Coffee
            [
                'category_id' => 3,
                'name' => 'Hazelnut Cream',
                'name_ar' => 'كريمة البندق',
                'slug' => 'hazelnut-cream',
                'description' => 'Smooth coffee infused with rich, creamy hazelnut flavor.',
                'description_ar' => 'قهوة ناعمة مشبعة بنكهة البندق الكريمية الغنية.',
                'price' => 280.00,
                'image' => 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=400&fit=crop',
                'stock' => 55,
                'weight' => '500g',
                'roast_level' => 'medium',
                'origin' => 'Flavored',
                'origin_ar' => 'منكّهة',
            ],
            [
                'category_id' => 3,
                'name' => 'Vanilla Caramel Swirl',
                'name_ar' => 'فانيليا كراميل',
                'slug' => 'vanilla-caramel-swirl',
                'description' => 'Sweet vanilla and caramel notes for a dessert-like experience.',
                'description_ar' => 'نكهات الفانيليا والكراميل الحلوة لتجربة تشبه الحلوى.',
                'price' => 290.00,
                'sale_price' => 249.00,
                'image' => 'https://images.unsplash.com/photo-1578374173705-969cbe6f2d6b?w=400&h=400&fit=crop',
                'stock' => 48,
                'weight' => '500g',
                'roast_level' => 'medium',
                'origin' => 'Flavored',
                'origin_ar' => 'منكّهة',
            ],
            [
                'category_id' => 3,
                'name' => 'Chocolate Mocha',
                'name_ar' => 'موكا شوكولاتة',
                'slug' => 'chocolate-mocha',
                'description' => 'Rich chocolate flavor blended with premium coffee beans.',
                'description_ar' => 'نكهة شوكولاتة غنية ممزوجة بحبوب قهوة فاخرة.',
                'price' => 310.00,
                'image' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&h=400&fit=crop',
                'stock' => 42,
                'weight' => '500g',
                'roast_level' => 'medium',
                'origin' => 'Flavored',
                'origin_ar' => 'منكّهة',
            ],
            [
                'category_id' => 3,
                'name' => 'Cinnamon Roll',
                'name_ar' => 'لفائف القرفة',
                'slug' => 'cinnamon-roll',
                'description' => 'Warm cinnamon spice with sweet frosting notes.',
                'description_ar' => 'توابل القرفة الدافئة مع نكهات الحلوى.',
                'price' => 275.00,
                'image' => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=400&fit=crop',
                'stock' => 38,
                'weight' => '500g',
                'roast_level' => 'medium',
                'origin' => 'Flavored',
                'origin_ar' => 'منكّهة',
            ],

            // Cold Brew
            [
                'category_id' => 4,
                'name' => 'Cold Brew Concentrate',
                'name_ar' => 'مركز القهوة الباردة',
                'slug' => 'cold-brew-concentrate',
                'description' => 'Smooth and naturally sweet cold brew concentrate. Just add water or milk.',
                'description_ar' => 'مركز قهوة باردة ناعم وحلو طبيعياً. أضف الماء أو الحليب فقط.',
                'price' => 260.00,
                'image' => 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=400&h=400&fit=crop',
                'stock' => 65,
                'weight' => '500ml',
                'roast_level' => 'medium',
                'origin' => 'Blend',
                'origin_ar' => 'مزيج',
                'is_featured' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Nitro Cold Brew Blend',
                'name_ar' => 'قهوة باردة نيترو',
                'slug' => 'nitro-cold-brew-blend',
                'description' => 'Specially roasted for the smoothest nitro cold brew experience.',
                'description_ar' => 'محمصة خصيصاً لأكثر تجربة قهوة نيترو باردة نعومة.',
                'price' => 340.00,
                'image' => 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=400&fit=crop',
                'stock' => 30,
                'weight' => '500g',
                'roast_level' => 'medium',
                'origin' => 'Blend',
                'origin_ar' => 'مزيج',
            ],
            [
                'category_id' => 4,
                'name' => 'Iced Coffee Blend',
                'name_ar' => 'خلطة القهوة المثلجة',
                'slug' => 'iced-coffee-blend',
                'description' => 'Bold and refreshing, perfect over ice.',
                'description_ar' => 'جريئة ومنعشة، مثالية مع الثلج.',
                'price' => 220.00,
                'image' => 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=400&fit=crop',
                'stock' => 58,
                'weight' => '500g',
                'roast_level' => 'medium',
                'origin' => 'Blend',
                'origin_ar' => 'مزيج',
            ],

            // Arabic Coffee
            [
                'category_id' => 5,
                'name' => 'Arabic Cardamom Coffee',
                'name_ar' => 'قهوة عربية بالهيل',
                'slug' => 'arabic-cardamom-coffee',
                'description' => 'Traditional Arabic coffee with premium cardamom. A taste of Arabian hospitality.',
                'description_ar' => 'قهوة عربية تقليدية مع الهيل الفاخر. طعم الضيافة العربية.',
                'price' => 300.00,
                'sale_price' => 269.00,
                'image' => 'https://images.unsplash.com/photo-1578374173705-969cbe6f2d6b?w=400&h=400&fit=crop',
                'stock' => 75,
                'weight' => '500g',
                'roast_level' => 'light',
                'origin' => 'Arabia',
                'origin_ar' => 'عربية',
                'is_featured' => true,
            ],
            [
                'category_id' => 5,
                'name' => 'Yemeni Mocha',
                'name_ar' => 'موكا يمني',
                'slug' => 'yemeni-mocha',
                'description' => 'The original mocha from Yemen. Complex with wine and chocolate notes.',
                'description_ar' => 'الموكا الأصلية من اليمن. معقدة مع نكهات النبيذ والشوكولاتة.',
                'price' => 650.00,
                'image' => 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop',
                'stock' => 15,
                'weight' => '250g',
                'roast_level' => 'light',
                'origin' => 'Yemen',
                'origin_ar' => 'اليمن',
            ],
            [
                'category_id' => 5,
                'name' => 'Turkish Coffee Blend',
                'name_ar' => 'مزيج القهوة التركية',
                'slug' => 'turkish-coffee-blend',
                'description' => 'Finely ground for traditional Turkish preparation. Rich and aromatic.',
                'description_ar' => 'مطحونة ناعماً للتحضير التركي التقليدي. غنية وعطرية.',
                'price' => 240.00,
                'image' => 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=400&h=400&fit=crop',
                'stock' => 80,
                'weight' => '500g',
                'roast_level' => 'medium',
                'origin' => 'Blend',
                'origin_ar' => 'مزيج',
            ],
            [
                'category_id' => 5,
                'name' => 'Egyptian Coffee Special',
                'name_ar' => 'قهوة مصرية خاصة',
                'slug' => 'egyptian-coffee-special',
                'description' => 'Our signature Egyptian-style blend with a hint of spice.',
                'description_ar' => 'مزيجنا المميز على الطريقة المصرية مع لمسة من التوابل.',
                'price' => 280.00,
                'image' => 'https://images.unsplash.com/photo-1504630083234-14187a9df0f5?w=400&h=400&fit=crop',
                'stock' => 90,
                'weight' => '500g',
                'roast_level' => 'medium',
                'origin' => 'Blend',
                'origin_ar' => 'مزيج',
                'is_featured' => true,
            ],
            [
                'category_id' => 5,
                'name' => 'Saffron Gold Coffee',
                'name_ar' => 'قهوة الزعفران الذهبية',
                'slug' => 'saffron-gold-coffee',
                'description' => 'Luxurious Arabic coffee with precious saffron threads.',
                'description_ar' => 'قهوة عربية فاخرة مع خيوط الزعفران الثمينة.',
                'price' => 750.00,
                'image' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&h=400&fit=crop',
                'stock' => 12,
                'weight' => '250g',
                'roast_level' => 'light',
                'origin' => 'Arabia',
                'origin_ar' => 'عربية',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }

        $this->command->info('✅ Database seeded successfully!');
        $this->command->info('📧 Admin: admin@empapy.com / password');
        $this->command->info('📧 Customer: customer@empapy.com / password');
    }
}
