server {
    listen 80;
    server_name empapy.com www.empapy.com;
    
    # تحويل أي حد يدخل HTTP يروح أوتوماتيك لـ HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name empapy.com www.empapy.com;

    # 🔒 مسارات شهادة الحماية الجديدة
    ssl_certificate /etc/letsencrypt/live/empapy.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/empapy.com/privkey.pem;

    # مسار المشروع جوه الكونتينر
    root /var/www/html/public;
    index index.php index.html;

    # Security headers (حماية إضافية)
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # إعدادات PHP للدوكر
    location ~ \.php$ {
        fastcgi_pass app:9000; # اسم الكونتينر app
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # منع الوصول للملفات الحساسة
    location ~ /\.(?!well-known).* {
        deny all;
    }
}